name: Terraform Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.5

      
      - name: Set up AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region us-east-1 # Set to your desired region
          echo "check aws cli identity"
          aws sts get-caller-identity


      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: tfplan

      - name: Check Terraform Plan Success
        id: check
        run: |
          terraform show -no-color tfplan | grep "No changes. Infrastructure is up-to-date."
        continue-on-error: true

      - name: Merge Branch to Main
        if: steps.check.outcome == 'success'
        uses: peter-evans/merge-action@v4
        with:
          source_branch: ${{ github.head_ref }}
          target_branch: main
          commit_message: "Automated merge of branch ${{ github.head_ref }} to main"

      - name: Notify on Failure
        if: steps.check.outcome != 'success'
        run: echo "Terraform plan did not succeed. No changes have been merged."
